// senha-vue/src/App.vue
<template>
  <main class="main">
    <div class="container">
      <h1 class="title">Gerador de Senhas</h1>
      <TamanhoInput v-model="tamanho" />
      <div class="checkboxContainer">
        <Checkbox v-for="(opcao, index) in tiposCaracteres" :key="opcao.id" :id="opcao.id" :texto="opcao.nome"
          :selecionado="opcao.valor" @mudanca="lidaComMudanca(index)" />
      </div>
      <button class="button" @click="gerarSenha">Gerar Senha</button>
    </div>
    <div class="container">
      <UltimasSenhas :senhas="senhasGeradas" />
    </div>
  </main>
</template>

<script>
import { ref } from 'vue';
import Checkbox from './components/Checkbox.vue';
import UltimasSenhas from './components/UltimasSenhas.vue';
import TamanhoInput from './components/TamanhoInput.vue';
import opcoes from '../../core/OpcoesCaracteres';
import Senha from '../../core/Senha';

export default {
  components: {
    Checkbox,
    UltimasSenhas,
    TamanhoInput,
  },
  setup() {
    const tamanho = ref(8);
    const tiposCaracteres = ref(opcoes);
    const senhasGeradas = ref([]);

    const lidaComMudanca = (indice) => {
      tiposCaracteres.value[indice].valor = !tiposCaracteres.value[indice].valor;
    };

    const gerarSenha = () => {
      const novaSenha = Senha.gerarSenha(tamanho.value, tiposCaracteres.value);
      senhasGeradas.value.unshift(novaSenha);
      senhasGeradas.value.splice(8);
    };

    return {
      tamanho,
      tiposCaracteres,
      senhasGeradas,
      lidaComMudanca,
      gerarSenha,
    };
  },
};
</script>

<style>
@import './styles.css';
</style>

// senha-next/src/app/page.tsx
"use client";
import { useState } from "react";
import opcoes from "../../../core/OpcoesCaracteres";
import Checkbox from "@/components/Checkbox";
import Senha from "../../../core/Senha";
import UltimasSenhas from "@/components/UltimasSenhas";
import TamanhoInput from "@/components/TamanhoInput";
import styles from './page.module.css';

export default function Home() {
    const [tamanho, setTamanho] = useState<number>(8);
    const [tiposCaracteres, setTiposCaracteres] = useState(opcoes);
    const [senha, setSenha] = useState("");
    const [senhasGeradas, setSenhasGeradas] = useState<string[]>([]);

    const lidaComMudanca = (indice: number) => {
        const aux = [...tiposCaracteres];
        aux[indice].valor = !aux[indice].valor;
        setTiposCaracteres([...aux]);
    };

    const gerarSenha = () => {
        const novaSenha = Senha.gerarSenha(tamanho, tiposCaracteres);
        setSenha(novaSenha);
        setSenhasGeradas((prev) => [novaSenha, ...prev.slice(0, 7)]);
    };

    return (
        <main className={styles.main}>
            <div className={styles.container}>
                <h1 className={styles.title}>Gerador de Senhas</h1>
                <TamanhoInput tamanho={tamanho} setTamanho={setTamanho} />
                <div className={styles.checkboxContainer}>
                    {tiposCaracteres.map((opcao, i) => (
                        <Checkbox
                            key={opcao.id}
                            id={opcao.id}
                            texto={opcao.nome}
                            selecionado={opcao.valor}
                            lidaComMudanca={() => lidaComMudanca(i)}
                        />
                    ))}
                </div>
                <button className={styles.button} onClick={gerarSenha}>
                    Gerar Senha
                </button>
            </div>
            <div className={styles.container}>
                <UltimasSenhas senhas={senhasGeradas} />
            </div>
        </main>
    );
}
