// senha-next/src/components/ExibeSenha.tsx
import { IconCopy } from "@tabler/icons-react";
import { useState } from "react";
import styles from '../app/page.module.css';

interface ExibeSenhaProps {
    senha: string;
}

export default function (props: ExibeSenhaProps) {
    const [mostrarAviso, setMostrarAviso] = useState(false);

    const copiar = () => {
        navigator.clipboard.writeText(props.senha);
        setMostrarAviso(true);
        setTimeout(() => {
            setMostrarAviso(false);
        }, 2000);
    };

    return (
        <div className={styles.senhaContainer}>
            {props.senha.trim() !== "" && (
                <>
                    <div className={styles.senhaBox}>
                        {props.senha}
                        <IconCopy className={styles.copiarIcone} onClick={copiar} />
                    </div>
                </>
            )}

            {mostrarAviso && (
                <p className={styles.copiadoAviso}>Senha copiada para área de transferência!</p>
            )}
        </div>
    );
}

// senha-angular/src/app/exibe-senha/exibe-senha.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-exibe-senha',
    templateUrl: './exibe-senha.component.html',
    styleUrls: ['./exibe-senha.component.css']
})
export class ExibeSenhaComponent {
    @Input() senha: string = '';
    mostrarAviso: boolean = false;

    copiar() {
        navigator.clipboard.writeText(this.senha).then(() => {
            this.mostrarAviso = true;
            setTimeout(() => {
                this.mostrarAviso = false;
            }, 2000);
        }).catch(err => {
            console.error('Erro ao copiar a senha: ', err);
        });
    }
}
<div *ngIf="senha.trim() !== ''" class="senhaContainer">
    <div class="senhaBox">
        {{ senha }}
        <span (click)="copiar()" class="copiarIcone">Copy</span>
    </div>
    <p *ngIf="mostrarAviso" class="copiadoAviso">Senha copiada!</p>
</div>
