// senha-vue/src/components/Checkbox.vue
<template>
    <div class="checkboxContainer">
        <input type="checkbox" :id="id" :checked="selecionado" @change="$emit('mudanca')" />
        <label :for="id">{{ texto }}</label>
    </div>
</template>

<script>
export default {
    props: {
        id: String,
        texto: String,
        selecionado: Boolean,
    },
};
</script>

// senha-angular/src/app/components/checkbox.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-checkbox',
  standalone: true,
  imports: [],
  template: `
    <div class="checkboxContainer">
      <input type="checkbox" [checked]="selecionado" (change)="toggleSelecionado()">
      <label>{{ texto }}</label>
    </div>
  `,
})

export class CheckboxComponent {
  @Input() texto: string = '';
  @Input() selecionado: boolean = false;
  @Output() lidaComMudanca = new EventEmitter<void>();

  toggleSelecionado() {
    this.lidaComMudanca.emit();
  }
}
<div class="checkbox-container">
  <input type="checkbox" [checked]="selecionado" (change)="toggleSelecionado()">
  <label>{{ texto }}</label>
</div>
