// senha-next/src/components/ExibeSenha.tsx
import { IconCopy } from "@tabler/icons-react";
import { useState } from "react";
import '../app/globals.css';

interface ExibeSenhaProps {
    senha: string;
}

export default function (props: ExibeSenhaProps) {
    const [mostrarAviso, setMostrarAviso] = useState(false);

    const copiar = () => {
        navigator.clipboard.writeText(props.senha);
        setMostrarAviso(true);
        setTimeout(() => {
            setMostrarAviso(false);
        }, 2000);
    };

    return (
        <div>
            {props.senha.trim() !== "" && (
                <div className={"senhaContainer"}>
                    {props.senha}
                    <IconCopy className={"copiarIcone"} onClick={copiar} />
                </div>
            )}

            {mostrarAviso && (
                <p className={"copiadoAviso"}>Senha copiada para área de transferência!</p>
            )}
        </div>
    );
}

// senha-angular/src/app/components/exibe-senha.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-exibe-senha',
  standalone: true,
  imports: [],
  template: `
    <div *ngIf="senha.trim() !== ''">
    <div class="senhaContainer">
        {{ senha }}
        <span (click)="copiar()" class="copiarIcone">Copy</span>
    </div>
    <p *ngIf="mostrarAviso" class="copiadoAviso">Senha copiada!</p>
</div>
  `,
})

export class ExibeSenhaComponent {
  @Input() senha: string = '';
  mostrarAviso: boolean = false;

  copiar() {
    navigator.clipboard.writeText(this.senha).then(() => {
      this.mostrarAviso = true;
      setTimeout(() => {
        this.mostrarAviso = false;
      }, 2000);
    }).catch(err => {
      console.error('Erro ao copiar a senha: ', err);
    });
  }
}
<div *ngIf="senha.trim() !== ''">
  <div class="senha-container">
    {{ senha }}
    <span (click)="copiar()">Copy</span>
  </div>
  <p *ngIf="mostrarAviso">Senha copiada!</p>
</div>
