// senha-angular/src/app/checkbox/checkbox.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'app-checkbox',
    templateUrl: './checkbox.component.html',
    styleUrls: ['./checkbox.component.css']
})
export class CheckboxComponent {
    @Input() texto: string = '';
    @Input() selecionado: boolean = false;
    @Output() lidaComMudanca = new EventEmitter<void>();

    toggleSelecionado() {
        this.lidaComMudanca.emit();
    }
}
<div class="checkboxItem">
    <input type="checkbox" [checked]="selecionado" (change)="toggleSelecionado()">
    <label>{{ texto }}</label>
</div>

// senha-next/src/components/Checkbox.tsx
import '../app/globals.css';

interface CheckboxProps {
    id: string;
    texto: string;
    selecionado: boolean;
    lidaComMudanca: () => void;
}

export default function (props: CheckboxProps) {
    const id = `checkbox-${props.id}`;
    return (
        <div className={"checkboxContainer"}>
            <input
                type="checkbox"
                checked={props.selecionado}
                onChange={props.lidaComMudanca}
                id={id}
            />
            <label htmlFor={id}>{props.texto}</label>
        </div>
    );
}
