// senha-vue/src/components/ExibeSenha.vue
<template>
    <div class="senha-container">
        <div v-if="senha.trim() !== ''">
            {{ senha }}
            <button @click="copiar">📋</button>
        </div>
        <p v-if="mostrarAviso">Senha copiada para área de transferência!</p>
    </div>
</template>

<script setup>
import { ref } from 'vue';

const props = defineProps({
    senha: String,
});

const mostrarAviso = ref(false);

const copiar = () => {
    navigator.clipboard.writeText(props.senha);
    mostrarAviso.value = true;
    setTimeout(() => {
        mostrarAviso.value = false;
    }, 2000);
};
</script>

// senha-next/src/components/ExibeSenha.tsx
import { IconCopy } from "@tabler/icons-react";
import { useState } from "react";
import '../app/globals.css';

interface ExibeSenhaProps {
    senha: string;
}

export default function (props: ExibeSenhaProps) {
    const [mostrarAviso, setMostrarAviso] = useState(false);

    const copiar = () => {
        navigator.clipboard.writeText(props.senha);
        setMostrarAviso(true);
        setTimeout(() => {
            setMostrarAviso(false);
        }, 2000);
    };

    return (
        <div>
            {props.senha.trim() !== "" && (
                <div className={"senha-container"}>
                    {props.senha}
                    <IconCopy className={"copiarIcone"} onClick={copiar} />
                </div>
            )}

            {mostrarAviso && (
                <p>Senha copiada para área de transferência!</p>
            )}
        </div>
    );
}
