// senha-angular/src/app/tamanho-input/tamanho-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'tamanho-input',
    templateUrl: './tamanho-input.component.html',
    styleUrls: ['./tamanho-input.component.css']
})
export class TamanhoInputComponent {
    @Input() tamanho: number = 8; // Valor padrão
    @Output() tamanhoChange: EventEmitter<number> = new EventEmitter<number>();

    onChange(value: number) {
        this.tamanho = value; // Atualiza o tamanho
        this.tamanhoChange.emit(this.tamanho); // Emite o valor atualizado
        console.log('Tamanho atualizado:', this.tamanho); // Log do valor atualizado
    }
}
<div>
    <label for="tamanho">Tamanho da Senha:</label>
    <input type="number" id="tamanho" [(ngModel)]="tamanho" (input)="onChange(tamanho)" min="1" />
</div>

// senha-next/src/components/TamanhoInput.tsx
import '../app/globals.css';

interface TamanhoInputProps {
    tamanho: number;
    setTamanho: (valor: number) => void;
}

export default function TamanhoInput({ tamanho, setTamanho }: TamanhoInputProps) {
    return (
        <div className="input-container">
            <label className={"input-label"}>
                Tamanho da Senha:
            </label>
            <input
                className={"input-number"}
                type="number"
                min={5}
                max={30}
                value={tamanho}
                onChange={(e) => setTamanho(+e.target.value)}
            />
        </div>
    );
}
