// senha-angular/src/app/components/tamanho-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-tamanho-input',
  standalone: true,
  imports: [FormsModule],
  template: `
<div class="inputContainer">
    <label class="inputLabel" for="tamanho">Tamanho da Senha:</label>
    <input class="inputNumber" type="number" id="tamanho" [(ngModel)]="tamanho" (input)="onChange(tamanho)" min="1" />
</div>
  `,
})


export class TamanhoInputComponent {
  @Input() tamanho: number = 8;
  @Output() tamanhoChange: EventEmitter<number> = new EventEmitter<number>();

  onChange(value: number) {
    this.tamanho = value;
    this.tamanhoChange.emit(this.tamanho);
  }
}
<div class="input-container">
  <label class="input-label" for="tamanho">Tamanho da Senha:</label>
  <input class="input-number" type="number" id="tamanho" [(ngModel)]="tamanho" (input)="onChange(tamanho)" min="1" />
</div>

// senha-next/src/components/TamanhoInput.tsx
import '../app/globals.css';

interface TamanhoInputProps {
    tamanho: number;
    setTamanho: (valor: number) => void;
}

export default function TamanhoInput({ tamanho, setTamanho }: TamanhoInputProps) {
    return (
        <div className="inputContainer">
            <label className={"inputLabel"}>
                Tamanho da Senha:
            </label>
            <input
                className={"inputNumber"}
                type="number"
                min={5}
                max={30}
                value={tamanho}
                onChange={(e) => setTamanho(+e.target.value)}
            />
        </div>
    );
}
