// senha-angular/src/app/components/ultimas-senhas.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ExibeSenhaComponent } from './exibe-senha.component';

@Component({
  selector: 'app-ultimas-senhas',
  standalone: true,
  imports: [CommonModule, ExibeSenhaComponent],
  templateUrl: './ultimas-senhas.component.html',
})
export class UltimasSenhasComponent {
  @Input() senhas: string[] = [];
}
<div>
  <h2 class="main-title">Últimas Senhas Geradas:</h2>
  <ul class="ultimas-list">
    <li *ngFor="let senha of senhas">
      <app-exibe-senha [senha]="senha"></app-exibe-senha>
    </li>
  </ul>
</div>

// senha-next/src/components/UltimasSenhas.tsx
import ExibeSenha from "./ExibeSenha";
import '../app/globals.css';

interface UltimasSenhasProps {
    senhas: string[];
}

export default function UltimasSenhas({ senhas }: UltimasSenhasProps) {
    return (
        <div>
            <h2 className="main-title">Últimas Senhas Geradas:</h2>
            <ul className="ultimas-list">
                {senhas.map((senha, index) => (
                    <li key={index}>
                        <ExibeSenha senha={senha} />
                    </li>
                ))}
            </ul>
        </div>
    );
}
