// senha-vue/src/components/UltimasSenhas.vue
<template>
    <div>
        <h2 class="main-title">Últimas Senhas Geradas:</h2>
        <ul class="ultimas-list">
            <li v-for="(senha, index) in senhas" :key="index">
                <ExibeSenha :senha="senha" />
            </li>
        </ul>
    </div>
</template>

<script setup>
import ExibeSenha from './ExibeSenha.vue';

const props = defineProps({
    senhas: Array,
});
</script>

// senha-next/src/components/UltimasSenhas.tsx
import ExibeSenha from "./ExibeSenha";
import '../app/globals.css';

interface UltimasSenhasProps {
    senhas: string[];
}

export default function UltimasSenhas({ senhas }: UltimasSenhasProps) {
    return (
        <div>
            <h2 className="main-title">Últimas Senhas Geradas:</h2>
            <ul className="ultimas-list">
                {senhas.map((senha, index) => (
                    <li key={index}>
                        <ExibeSenha senha={senha} />
                    </li>
                ))}
            </ul>
        </div>
    );
}
