// senha-vue/src/App.vue
<template>
  <main class="main">
    <div class="mainContainer">
      <h1 class="mainTitle">Gerador de Senhas</h1>
      <TamanhoInput v-model="tamanho" />
      <div class="checkboxContainer">
        <Checkbox v-for="(opcao, index) in tiposCaracteres" :key="opcao.id" :id="opcao.id" :texto="opcao.nome"
          :selecionado="opcao.valor" @mudanca="lidaComMudanca(index)" />
      </div>
      <button class="mainButton" @click="gerarSenha">Gerar Senha</button>
    </div>
    <div class="mainContainer">
      <UltimasSenhas :senhas="senhasGeradas" />
    </div>
  </main>
</template>

<script>
import { ref } from 'vue';
import Checkbox from './components/Checkbox.vue';
import UltimasSenhas from './components/UltimasSenhas.vue';
import TamanhoInput from './components/TamanhoInput.vue';
import opcoes from '../../core/OpcoesCaracteres';
import Senha from '../../core/Senha';

export default {
  components: {
    Checkbox,
    UltimasSenhas,
    TamanhoInput,
  },
  setup() {
    const tamanho = ref(8);
    const tiposCaracteres = ref(opcoes);
    const senhasGeradas = ref([]);

    const lidaComMudanca = (indice) => {
      tiposCaracteres.value[indice].valor = !tiposCaracteres.value[indice].valor;
    };

    const gerarSenha = () => {
      const novaSenha = Senha.gerarSenha(tamanho.value, tiposCaracteres.value);
      senhasGeradas.value.unshift(novaSenha);
      senhasGeradas.value.splice(8);
    };

    return {
      tamanho,
      tiposCaracteres,
      senhasGeradas,
      lidaComMudanca,
      gerarSenha,
    };
  },
};
</script>

<style>
@import './styles.css';
</style>

// senha-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import OpcaoCaractere from './core/OpcaoCaractere';
import Senha from './core/Senha';
import opcoesCaracteres from './core/OpcoesCaracteres';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['../styles.css']
})
export class AppComponent {
  tamanho: number = 8;
  tiposCaracteres: OpcaoCaractere[] = opcoesCaracteres;
  senhasGeradas: string[] = ['sadsadadsad', 'sadasdasdsad'];

  gerarSenha() {
    const senhaGerada = Senha.gerarSenha(this.tamanho, this.tiposCaracteres);
    this.senhasGeradas.unshift(senhaGerada);

    if (this.senhasGeradas.length > 10) {
      this.senhasGeradas.pop();
    }
  }

  lidaComMudanca(index: number) {
    this.tiposCaracteres[index].valor = !this.tiposCaracteres[index].valor;
  }

  onTamanhoChange(novoTamanho: number) {
    this.tamanho = novoTamanho;
  }
}
<div class="main">
  <div class="mainContainer">
    <h1 class="mainTitle">Gerador de Senhas</h1>
    <app-tamanho-input [(tamanho)]="tamanho" (tamanhoChange)="onTamanhoChange($event)"></app-tamanho-input>
    <div class="checkboxContainer">
      <app-checkbox *ngFor="let opcao of tiposCaracteres; let i = index" [id]="opcao.id" [texto]="opcao.nome"
        [selecionado]="opcao.valor" (lidaComMudanca)="lidaComMudanca(i)">
      </app-checkbox>
    </div>
    <button class="mainButton" (click)="gerarSenha()">Gerar Senha</button>
  </div>
  <div class="mainContainer">
    <app-ultimas-senhas [senhas]="senhasGeradas"></app-ultimas-senhas>
  </div>
</div>
