// senha-next/src/components/Checkbox.tsx
import '../app/globals.css';

interface CheckboxProps {
    id: string;
    texto: string;
    selecionado: boolean;
    lidaComMudanca: () => void;
}

export default function (props: CheckboxProps) {
    const id = `checkbox-${props.id}`;
    return (
        <div className={"checkboxContainer"}>
            <input
                type="checkbox"
                checked={props.selecionado}
                onChange={props.lidaComMudanca}
                id={id}
            />
            <label htmlFor={id}>{props.texto}</label>
        </div>
    );
}

// senha-vue/src/components/Checkbox.vue
<template>
    <div class="checkboxContainer">
        <input type="checkbox" :id="id" :checked="selecionado" @change="$emit('mudanca')" />
        <label :for="id">{{ texto }}</label>
    </div>
</template>

<script>
export default {
    props: {
        id: String,
        texto: String,
        selecionado: Boolean,
    },
};
</script>
