// senha-next/src/components/TamanhoInput.tsx
import '../app/globals.css';

interface TamanhoInputProps {
    tamanho: number;
    setTamanho: (valor: number) => void;
}

export default function TamanhoInput({ tamanho, setTamanho }: TamanhoInputProps) {
    return (
        <div className="inputContainer">
            <label className={"inputLabel"}>
                Tamanho da Senha:
            </label>
            <input
                className={"inputNumber"}
                type="number"
                min={5}
                max={30}
                value={tamanho}
                onChange={(e) => setTamanho(+e.target.value)}
            />
        </div>
    );
}

// senha-vue/src/components/TamanhoInput.vue
<template>
    <div class="inputContainer">
        <label class="inputLabel">
            Tamanho da Senha:
        </label>
        <input type="number" min="5" max="30" :value="tamanho"
                @input="$emit('update:modelValue', +$event.target.value)" class="inputNumber" />
    </div>
</template>

<script>
export default {
    props: {
        modelValue: Number,
    },
    computed: {
        tamanho: {
            get() {
                return this.modelValue;
            },
            set(value) {
                this.$emit('update:modelValue', value);
            },
        },
    },
};
</script>
